include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_dynamic_calls: false
    prefer_single_quotes: true
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    directives_ordering: false
    avoid_unnecessary_containers: false
    prefer_if_elements_to_conditional_expressions: false
    require_trailing_commas: false